Address PR comments
- Add myself as contributor
- Test for existence of `toHex` and `fromHex` only once
- Upgrade Node types
- Remove `as any`, which required:
  - Adding TypeScript as an explicit dependency to be able to update it to 6.0 (first version to support `toHex` and `fromHex`)
  - Upgrading `typedoc` and `typescript-eslint` to have them support TypeScript 6
  - Tweak `tsconfig.json`:
    - Add `ESNext` to `lib` to support `toHex` and `fromHex`
    - Set `rootDir` to `./src` to address the following error on `outDir`: `The common source directory of 'tsconfig.json' is './src'. The 'rootDir' setting must be explicitly set to this or another path to adjust your output's file layout. Visit https://aka.ms/ts6 for migration information.`
    - Add `"ignoreDeprecations": "6.0"` to silence `error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.`. We actually don't set `baseUrl`, so I supposed a tool in our tool chain sets it.